# Generated by Django 5.2.1 on 2025-05-30 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Produto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descricao", models.CharField(max_length=50)),
                ("cod", models.CharField(max_length=15)),
                (
                    "und_medida",
                    models.CharField(
                        choices=[("lt", "Litro"), ("cx", "Caixa"), ("und", "Unidade")],
                        max_length=15,
                    ),
                ),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("comp_eletron", "Componentes Eletrônicos"),
                            ("resinas", "Resinas"),
                            ("filamento", "Filamento para impressão"),
                        ],
                        max_length=30,
                    ),
                ),
                ("qtd_estoque", models.IntegerField()),
            ],
        ),
    ]
